basePath: /
definitions:
  model.Driver:
    properties:
      driver_id:
        type: integer
      driver_license:
        type: string
      driver_name:
        type: string
      home_town:
        type: string
    required:
    - driver_id
    - driver_license
    type: object
host: 172.18.53.136:8080
info:
  contact: {}
  description: This is a sample server for the IoT Project API.
  title: IoT Proecjt
  version: "1.0"
paths:
  /drivers:
    post:
      consumes:
      - application/json
      description: Create a new driver
      parameters:
      - description: driver object that needs to be added
        in: body
        name: driver
        required: true
        schema:
          $ref: '#/definitions/model.Driver'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create a new driver
      tags:
      - driver
schemes:
- http
- https
swagger: "2.0"
