basePath: /
definitions:
  controller.DriverServerResponse:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
  controller.VehicleServerResponse:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
  model.Driver:
    properties:
      driver_id:
        type: integer
      driver_license:
        type: string
      driver_name:
        type: string
      home_town:
        type: string
    required:
    - driver_id
    - driver_license
    type: object
  model.Vehicle:
    properties:
      vehicle_id:
        type: integer
      vehicle_name:
        type: string
      vehicle_plate:
        type: string
    required:
    - vehicle_id
    - vehicle_plate
    type: object
host: 192.168.88.132:9090
info:
  contact: {}
  description: This is a sample server for the IoT Project API.
  title: IoT Proecjt
  version: "1.0"
paths:
  /drivers:
    get:
      consumes:
      - application/json
      description: Get all drivers from the database and returns them as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: List of drivers
          schema:
            $ref: '#/definitions/controller.DriverServerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.DriverServerResponse'
      summary: Get all drivers
      tags:
      - Driver
    post:
      consumes:
      - application/json
      description: Create a new driver
      parameters:
      - description: driver object that needs to be added
        in: body
        name: driver
        required: true
        schema:
          $ref: '#/definitions/model.Driver'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create a new driver
      tags:
      - Driver
  /drivers/{driverID}:
    delete:
      consumes:
      - application/json
      description: Delete a driver from the database based on its ID.
      parameters:
      - description: Driver ID
        in: path
        name: driverID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Driver deleted successfully
          schema:
            $ref: '#/definitions/controller.DriverServerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.DriverServerResponse'
      summary: Delete a driver
      tags:
      - Driver
    get:
      consumes:
      - application/json
      description: Retrieve a driver from the database by its ID and return it as
        JSON.
      parameters:
      - description: Driver ID
        in: path
        name: driverID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Driver information
          schema:
            $ref: '#/definitions/controller.DriverServerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.DriverServerResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.DriverServerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.DriverServerResponse'
      summary: Retrieve a driver by ID
      tags:
      - Driver
    put:
      consumes:
      - application/json
      description: Update information of a driver based on the provided data in JSON
        format.
      parameters:
      - description: Driver ID
        in: path
        name: driverID
        required: true
        type: string
      - description: Driver object to be updated
        in: body
        name: driver
        required: true
        schema:
          $ref: '#/definitions/model.Driver'
      produces:
      - application/json
      responses:
        "200":
          description: Updated driver information
          schema:
            $ref: '#/definitions/controller.DriverServerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.DriverServerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.DriverServerResponse'
      summary: Update a driver
      tags:
      - Driver
  /vehicles:
    get:
      description: Retrieve all vehicles stored in the database
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/controller.VehicleServerResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.VehicleServerResponse'
      summary: Retrieve all vehicles
      tags:
      - Vehicle
    post:
      consumes:
      - application/json
      description: Create a new vehicle with the provided information
      parameters:
      - description: Vehicle information
        in: body
        name: vehicle
        required: true
        schema:
          $ref: '#/definitions/model.Vehicle'
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/controller.VehicleServerResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/controller.VehicleServerResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.VehicleServerResponse'
      summary: Create a new vehicle
      tags:
      - Vehicle
    put:
      consumes:
      - application/json
      description: Update an existing vehicle with the provided information
      parameters:
      - description: Vehicle information
        in: body
        name: vehicle
        required: true
        schema:
          $ref: '#/definitions/model.Vehicle'
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/controller.VehicleServerResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/controller.VehicleServerResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.VehicleServerResponse'
      summary: Update a vehicle
      tags:
      - Vehicle
  /vehicles/{vehicleID}:
    delete:
      description: Delete a vehicle from the database by its ID
      parameters:
      - description: Vehicle ID
        in: path
        name: vehicleID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/controller.VehicleServerResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.VehicleServerResponse'
      summary: Delete a vehicle
      tags:
      - Vehicle
    get:
      description: Retrieve a vehicle from the database by its unique identifier
      parameters:
      - description: Vehicle ID
        in: path
        name: vehicleID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/controller.VehicleServerResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.VehicleServerResponse'
      summary: Retrieve a vehicle by its ID
      tags:
      - Vehicle
schemes:
- http
- https
swagger: "2.0"
